platform :ios, '9.0'

def common
  pod 'MBProgressHUD'
end

target 'Example-OC' do
    use_frameworks!
    common
end

target 'Example-Swift' do
  use_frameworks!
  common
  pod 'CSHud', :path=>'./../CSHud.podspec'
end
